Update notebooks, add deployment artifacts and update deployment pipeline

diff --git a/ado_pipelines/model_deployment_pipeline.yml b/ado_pipelines/model_deployment_pipeline.yml
--- a/ado_pipelines/model_deployment_pipeline.yml
+++ b/ado_pipelines/model_deployment_pipeline.yml
@@ -2,10 +2,14 @@
 
 # Runtime parameters to select artifacts
 parameters:
-- name : artifactBuildId
-  displayName: Model Train CI Build ID. Default is 'latest'.
+- name : paramModelName
+  displayName: Name of the model to be deployed
   type: string
-  default: latest
+  default: dog_clf_model
+- name : paramModelVersion
+  displayName: Version of the model to be deployed
+  type: string
+  default: 1
 
 pr: none
 
@@ -30,93 +34,87 @@ variables:
 stages:
 - stage: 'Deploy_ACI'
   displayName: 'Deploy to ACI'
-  condition: variables['ACI_DEPLOYMENT_NAME']
+  # condition: variables['ACI_DEPLOYMENT_NAME']
   jobs:
   - job: "Deploy_ACI"
     displayName: "Deploy to ACI"
     container: mlops
     timeoutInMinutes: 0
     steps:
-    - download: none
-    - template: diabetes_regression-get-model-id-artifact-template.yml
-      parameters:
-        projectId: '$(resources.pipeline.model-train-ci.projectID)'
-        pipelineId: '$(resources.pipeline.model-train-ci.pipelineID)'
-        artifactBuildId: ${{ parameters.artifactBuildId }}
     - task: AzureCLI@1
       displayName: 'Install AzureML CLI'
       inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+        azureSubscription: '$(paramWorkspaceServiceConnectionName)'
         scriptLocation: inlineScript
         workingDirectory: $(Build.SourcesDirectory)
         inlineScript: 'az extension add -n azure-cli-ml'
     - task: AzureCLI@1
       displayName: "Deploy to ACI (CLI)"
       inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+        azureSubscription: '$(paramWorkspaceServiceConnectionName)'
         scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
+        workingDirectory: $(Build.SourcesDirectory)/$(paramSourceDirectory)/deployment
         inlineScript: |
           set -e # fail on error
           
-          az ml model deploy --name $(ACI_DEPLOYMENT_NAME) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
+          az ml model deploy --name $(paramACIDeploymentName) --model '$(paramModelName):$(paramModelVersion)' \
           --ic inference_config.yml \
           --dc deployment_config_aci.yml \
-          -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
+          -g $(paramResourceGroupName) --workspace-name $(paramWorkspaceName) \
           --overwrite -v
-    - task: AzureCLI@1
-      displayName: 'Smoke test'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m ml_service.util.smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
+    # - task: AzureCLI@1
+    #   displayName: 'Smoke test'
+    #   inputs:
+    #     azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+    #     scriptLocation: inlineScript
+    #     inlineScript: |
+    #       set -e # fail on error
+    #       export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+    #       python -m testing.smoke.test_model_endpoint --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
 
-- stage: 'Deploy_AKS'
-  displayName: 'Deploy to AKS'
-  dependsOn: Deploy_ACI
-  condition: and(succeeded(), variables['AKS_DEPLOYMENT_NAME'])
-  jobs:
-  - job: "Deploy_AKS"
-    displayName: "Deploy to AKS"
-    container: mlops
-    timeoutInMinutes: 0
-    steps:
-    - template: diabetes_regression-get-model-id-artifact-template.yml
-      parameters:
-        projectId: '$(resources.pipeline.model-train-ci.projectID)'
-        pipelineId: '$(resources.pipeline.model-train-ci.pipelineID)'
-        artifactBuildId: ${{ parameters.artifactBuildId }}
-    - task: AzureCLI@1
-      displayName: 'Install AzureML CLI'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: 'az extension add -n azure-cli-ml'
-    - task: AzureCLI@1
-      displayName: "Deploy to AKS (CLI)"
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
-        inlineScript: |
-          set -e # fail on error
+# - stage: 'Deploy_AKS'
+#   displayName: 'Deploy to AKS'
+#   dependsOn: Deploy_ACI
+#   condition: and(succeeded(), variables['AKS_DEPLOYMENT_NAME'])
+#   jobs:
+#   - job: "Deploy_AKS"
+#     displayName: "Deploy to AKS"
+#     container: mlops
+#     timeoutInMinutes: 0
+#     steps:
+#     - template: diabetes_regression-get-model-id-artifact-template.yml
+#       parameters:
+#         projectId: '$(resources.pipeline.model-train-ci.projectID)'
+#         pipelineId: '$(resources.pipeline.model-train-ci.pipelineID)'
+#         artifactBuildId: ${{ parameters.artifactBuildId }}
+#     - task: AzureCLI@1
+#       displayName: 'Install AzureML CLI'
+#       inputs:
+#         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+#         scriptLocation: inlineScript
+#         workingDirectory: $(Build.SourcesDirectory)
+#         inlineScript: 'az extension add -n azure-cli-ml'
+#     - task: AzureCLI@1
+#       displayName: "Deploy to AKS (CLI)"
+#       inputs:
+#         azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+#         scriptLocation: inlineScript
+#         workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
+#         inlineScript: |
+#           set -e # fail on error
           
-          az ml model deploy --name $(AKS_DEPLOYMENT_NAME) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
-          --compute-target $(AKS_COMPUTE_NAME) \
-          --ic inference_config.yml \
-          --dc deployment_config_aks.yml \
-          -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
-          --overwrite -v
-    - task: AzureCLI@1
-      displayName: 'Smoke test'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m ml_service.util.smoke_test_scoring_service --type AKS --service "$(AKS_DEPLOYMENT_NAME)"
+#           az ml model deploy --name $(AKS_DEPLOYMENT_NAME) --model '$(MODEL_NAME):$(get_model.MODEL_VERSION)' \
+#           --compute-target $(AKS_COMPUTE_NAME) \
+#           --ic inference_config.yml \
+#           --dc deployment_config_aks.yml \
+#           -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
+#           --overwrite -v
+    # - task: AzureCLI@1
+    #   displayName: 'Smoke test'
+    #   inputs:
+    #     azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+    #     scriptLocation: inlineScript
+    #     inlineScript: |
+    #       set -e # fail on error
+    #       export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+    #       python -m ml_service.util.smoke_test_scoring_service --type AKS --service "$(AKS_DEPLOYMENT_NAME)"
